# Generated by Django 3.0.2 on 2020-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Contact_No', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
