# Generated by Django 3.0.2 on 2020-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Contact_No',
            new_name='ContactNo',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='firt_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
