# Generated by Django 3.0.2 on 2020-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200109_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ContactNo',
            field=models.CharField(max_length=100),
        ),
    ]
