# Generated by Django 3.0.2 on 2020-01-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200109_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('college', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
